### ISSUE TITLE
Frogger Syntax Error

### ISSUE THREAD

**Issue by JohnBMel** [CheungChang7/TI99_HOMEBREW#1]
Hi CheungChang7,

I receive "syntax error in 120" when attempting to run Frogger using the Classic99 emulator. I have not tried to run on my TI99/4a physical hardware.

Quick note - your Wordle TI port is excellent. Well done and thank you.

**Comment by CheungChang7** [comment]
It was written on the Classic99 emulator. I assume you are trying to run the Extended Basic program and not the binary. I believe you'll need to have XB256 loaded to run it since it uses a call to CALL LINK("CWRITE",A$) to load the compressed sound tables.

**Comment by CheungChang7** [comment]
down loaded source file and ran it on Classi99 emulator with XB256 loaded. Ran successfully with no issues.
